# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8a410984997228d5627216da08c6b05b4cfbe47670480644e5f4d82452626ecbc5d5cef9f3d2bb74ff155ea493b6fbd9786f3729a22e57d78194185eb6cab3

test:
  secret_key_base: 804a8ebdbeebc964c9b43f6b67f44341337a994fa4d21e2f922c867f1cb9109a91be408a584524a78f2a81392918a097ece2bf3b8b89e68cf789a1488cbb359c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
